print('hello world')

In [4]:
print('hello world')

hello world


In [5]:
'hello'

'hello'

# biaoti

## 2jibiaoti

**B**

*B*

~~B~~

[Baidu](http://www.baidu.com)

![Baidu](http://www.baidu.com)

> 蒹葭苍苍  
白露为霜

$x + y = 3$

$$ x * y = 2$$

In [54]:
import numpy as np

In [56]:
arr1 = np.array([1])

TypeError: 'tuple' object is not callable

In [11]:
arr1

(['1', '2'], ['3', '4'])

In [53]:
print(arr1.ndim)

AttributeError: 'tuple' object has no attribute 'ndim'

In [41]:
zarr = np.zeros(5)

In [68]:
zarr.dtype

dtype('float64')

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr2=np.array([6, 2, -7, 2, 8, -2, -1])

TypeError: 'tuple' object is not callable

In [22]:
arr2

[6, 2, -7, 2, 8, -2, -1]

In [80]:
arr3=np.array([10, 12, 14, 16, 18, 20])

TypeError: 'tuple' object is not callable

In [24]:
arr3

([1, 3, 5], [2, 4, 6])

In [25]:
arr2.shape

AttributeError: 'list' object has no attribute 'shape'

In [62]:
(1,2)

(1, 2)

In [71]:
arr_even = np.arange(10,21,2)

In [72]:
arr_even

array([10, 12, 14, 16, 18, 20])

In [73]:
arr_even.ndim

1

In [74]:
arr_even.shape

(6,)

In [75]:
arr_even.size

6

In [76]:
arr_even.dtype

dtype('int64')