In [1]:
import numpy as np

In [24]:
arr1 = np.array([1,3,2,4,9])

In [25]:
arr1

array([1, 3, 2, 4, 9])

In [26]:
arr2=np.ones(5)

In [27]:
arr2

array([1., 1., 1., 1., 1.])

In [29]:
arr3=np.zeros(3)

In [30]:
arr3

array([0., 0., 0.])

In [39]:
arr4=np.concatenate([arr1,arr2,arr3])

In [40]:
arr4

array([1., 2., 3., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [36]:
arr1.sort()

In [37]:
arr1

array([1, 2, 3, 4, 9])

In [42]:
arr1[2]

np.int64(3)

In [43]:
arr1[-3]

np.int64(3)

In [45]:
arr1[1:4]

array([2, 3, 4])

In [46]:
arr1+arr2

array([ 2.,  3.,  4.,  5., 10.])

In [47]:
arr1*-5

array([ -5, -10, -15, -20, -45])

In [52]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


In [55]:
arr1[(arr1<5)&(arr1>2)]

array([3, 4])

In [56]:
arr1<5

array([ True,  True,  True,  True, False])